source-file ~/.config/tmux/tmux.reset.conf
set -g default-terminal "tmux-256color"

set -g prefix ^A

# Mouse support
set -g mouse on

# Windows and Panes start with 1
set -g base-index 1
set -g status-position bottom
set -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set-option -g set-clipboard on
# Personal machine only: set SSH agent socket if ssh-agent is running
if-shell "[ -S \"$XDG_RUNTIME_DIR/ssh-agent.socket\" ]" \
  "set-environment -g SSH_AUTH_SOCK \"$XDG_RUNTIME_DIR/ssh-agent.socket\""

# Plugins managed by TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'catppuccin/tmux'
set -g @continuum-restore 'on'

# Catppuccin configuration
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
set -g @catppuccin_status_modules_right "directory" # date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"

set -g automatic-rename off
set -g allow-passthrough on

set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

set -g @yank_action 'copy-pipe'

# Personal machine only: use fish if available
if-shell "command -v fish" "set-option -g default-command fish"

# TPM initialization (must be last)
run '~/.config/tmux/plugins/tpm/tpm'
