# Windowrules
windowrule = workspace 1 silent, match:class ^(vivaldi-stable|Vivaldi)$

$gameApps = UnrealEditor|Godot
windowrule = workspace 4 silent, match:class ^($gameApps)$

$msgApps = org.telegram.desktop|vivaldi-web.whatsapp.com__-Default|discord
windowrule = group set always lock invade, workspace 5 silent, match:class ^($msgApps)$

$utilApps = vivaldi-calendar.google.com__calendar_-Default|vivaldi-www.gmail.com__-Default|vivaldi-outlook.office.com__mail_-Default
windowrule = group set always lock invade, workspace 6 silent, match:class ^($utilApps)$

$aiApps = vivaldi-chat.deepseek.com__-Default|vivaldi-chatgpt.com__-Default|vivaldi-claude.ai__-Default
windowrule = group set always lock invade, workspace special:scratchpad silent, match:class ^($aiApps)$

# Extra autostart processes
exec-once = uwsm app -- hyprsunset

# Workspace 1 - Browser
exec-once = [workspace 1 silent] vivaldi

# Workspace 2 - Notes
exec-once = [workspace 2 silent] ghostty

# Workspace 3 - Code

# Workspace 4 - Test

# Workspace 5 - Social
exec-once = [workspace 5 silent] discord
exec-once = [workspace 5 silent] Telegram
exec-once = [workspace 5 silent] omarchy-launch-webapp 'https://web.whatsapp.com/'

# Workspace 6 - Admin
exec-once = [workspace 6 silent] omarchy-launch-webapp "https://outlook.office.com/mail/"
exec-once = [workspace 6 silent] omarchy-launch-webapp "https://www.gmail.com/"
exec-once = [workspace 6 silent] omarchy-launch-webapp "https://calendar.google.com/calendar/"
