# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT ALT, W, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT ALT, O, Outlook, exec, omarchy-launch-webapp "https://outlook.office.com/mail/"
bindd = SUPER SHIFT ALT, G, Gmail, exec, omarchy-launch-webapp "https://www.gmail.com/"
bindd = SUPER SHIFT ALT, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar/"
bindd = SUPER SHIFT ALT, T, Telegram, exec, Telegram

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# Overwrite move focus
unbind = SUPER, H
bindd = SUPER, H, Move window focus left, movefocus, l
unbind = SUPER, L
bindd = SUPER, L, Move window focus right, movefocus, r
unbind = SUPER, K
bindd = SUPER, K, Move window focus up, movefocus, u
unbind = SUPER, J
bindd = SUPER, J, Move window focus down, movefocus, d

unbind = SUPER, P
bindd = SUPER, P, Toggle window split, togglesplit, # dwindle

# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
unbind = SUPER SHIFT, H
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
unbind = SUPER SHIFT, L
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
unbind = SUPER SHIFT, K
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
unbind = SUPER SHIFT, J
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

unbind = SUPER, T
bindd = SUPER, T, Show key bindings, exec, omarchy-menu-keybindings
